(function() {
 var root=this;
var fan=root.fan;
if (!fan && (typeof require !== 'undefined')) fan = require('sys.js');

 var c=fan.sys.MimeType.cache$;
 
c("as","text/plain; charset=utf-8");
c("atom","application/atom+xml");
c("c","text/plain; charset=utf-8");
c("class","application/java");
c("cpp","text/plain; charset=utf-8");
c("cs","text/plain; charset=utf-8");
c("css","text/css; charset=utf-8");
c("csv","text/csv");
c("doc","application/msword");
c("docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");
c("dump","application/octet-stream");
c("exe","application/octet-stream");
c("fan","text/plain; charset=utf-8");
c("fandoc","text/plain; charset=utf-8");
c("fansym","text/plain; charset=utf-8");
c("fog","text/plain; charset=utf-8");
c("gif","image/gif");
c("gtar","application/x-gtar");
c("gz","application/x-gzip");
c("gzip","application/x-gzip");
c("h","text/plain; charset=utf-8");
c("htm","text/html; charset=utf-8");
c("html","text/html; charset=utf-8");
c("ico","image/x-icon");
c("ics","text/calendar");
c("java","text/plain");
c("jpeg","image/jpeg");
c("jpg","image/jpeg");
c("log","text/plain; charset=utf-8");
c("js","text/javascript; charset=utf-8");
c("json","application/json");
c("jsonld","application/ld+json");
c("map","application/json");
c("mp3","audio/mpeg3");
c("mpeg","video/mpeg");
c("obix","text/xml; charset=utf-8");
c("oga","audio/ogg");
c("ogg","audio/ogg");
c("ogv","video/ogg");
c("otf","font/otf");
c("pdf","application/pdf");
c("png","image/png");
c("pod","application/zip");
c("ppt","application/vnd.ms-powerpoint");
c("pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation");
c("props","text/plain; charset=utf-8");
c("properties","text/plain; charset=utf-8");
c("rss","application/rss+xml");
c("svg","image/svg+xml; charset=utf-8");
c("swf","application/x-shockwave-flash");
c("tar","application/x-tar");
c("txt","text/plain; charset=utf-8");
c("text","text/plain; charset=utf-8");
c("tiff","image/tiff");
c("trio","text/trio; charset=utf-8");
c("ttf","font/ttf");
c("ttl","text/turtle");
c("tsv","text/tab-separated-values");
c("wav","audio/wav");
c("woff","font/woff");
c("woff2","font/woff2");
c("xhtml","application/xhtml+xml");
c("xls","application/vnd.ms-excel");
c("xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
c("xml","text/xml; charset=utf-8");
c("zip","application/zip");
c("zinc","text/zinc; charset=utf-8");
}).call(this);
